DROP TABLE IF EXISTS TBL_PRODUCTS;
CREATE TABLE TBL_PRODUCTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    prd_category VARCHAR(250) NOT NULL,
    prd_name VARCHAR(250) NOT NULL,
    prd_price NUMERIC(20, 2) DEFAULT 0
);